// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hzwyanistlqilkpurgek.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh6d3lhbmlzdGxxaWxrcHVyZ2VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczMTQ4MzEsImV4cCI6MjA3Mjg5MDgzMX0.vZ0Sanc5-dDJva0WC1LaW6leEUb-k8mPnroT5q75p4M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});